# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.6-browsers`
      # - image: ashander/miniconda3gcc
      - image: continuumio/miniconda3
      # continuumio/miniconda3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.1-dependencies-{{ checksum "environment.yml" }}

      - run:
          name: install dependencies
          command: |
            ENVS=$(conda env list | awk '{print $1}' )
            echo $ENVS
            if ! [[ $ENVS = *"ud2pos"* ]]; then
              source /opt/conda/etc/profile.d/conda.sh
              conda update -y -n base -c defaults conda
              conda env create -f environment.yml
            else
              echo "Conda env already installed"
            fi;

      - save_cache:
          key: v1.1-dependencies-{{ checksum "environment.yml" }}
          paths:
            - /opt/conda

      - run:
          name: run linter src
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate ud2pos
            pylint src/ --rcfile .pylintrc

      - run:
          name: run linter ud2pos
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate ud2pos
            pylint ud2pos/ --rcfile .pylintrc

      - store_artifacts:
          path: test-reports
          destination: test-reports
